# Generated by Django 4.2.5 on 2024-02-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='editprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mailid', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='profileimages/')),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('pcontactno', models.CharField(max_length=12)),
                ('pemail', models.CharField(max_length=40)),
                ('pstatus', models.BooleanField()),
                ('pservicetype', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=40)),
                ('peducation', models.CharField(max_length=40)),
                ('pDOB', models.DateField()),
                ('pimage', models.ImageField(upload_to='profileimages/')),
                ('password', models.IntegerField(default=1234)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('stype', models.CharField(max_length=20)),
                ('sprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='providerpaymentdetails',
            fields=[
                ('payid', models.IntegerField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=20)),
                ('appid', models.IntegerField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.service')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.service'),
        ),
    ]
