# Generated by Django 4.2.7 on 2024-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_exp_provider_pdob_provider_peducation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
