# Generated by Django 4.2.7 on 2024-01-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_service_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='password',
            field=models.IntegerField(default=1234),
        ),
    ]
