# Generated by Django 4.2.7 on 2024-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_provider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
