# Generated by Django 4.2.7 on 2024-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_userdetails_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='firstname',
            field=models.CharField(default='DefaultFirstName', max_length=30),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(default='DefaultLastName', max_length=30),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='mail',
            field=models.CharField(default='DefaultMail', max_length=30),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userid',
            field=models.CharField(default='abc', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='DefaultGender', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
