# Generated by Django 4.2.7 on 2024-01-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_userdetails_id_remove_userdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
