# Generated by Django 4.2.5 on 2024-01-28 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_userdetails_userid_userdetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Profile Images/'),
            preserve_default=False,
        ),
    ]
