# Generated by Django 4.2.5 on 2024-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_userdetails_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='images',
            field=models.ImageField(upload_to='ProfileImages/'),
        ),
    ]
