# Generated by Django 4.2.7 on 2024-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_userdetails_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=45)),
                ('service', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
            ],
        ),
    ]
