# Generated by Django 4.2.7 on 2024-01-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_appointmentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='phoneno',
            field=models.IntegerField(default='123'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='workers',
            field=models.IntegerField(default='123'),
        ),
    ]
