# Generated by Django 4.2.7 on 2024-02-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_appointmentdetails_phoneno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='mail',
        ),
    ]
