# Generated by Django 4.2.7 on 2024-02-04 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_userdetails_id_appointmentdetails_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='appid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
