# Generated by Django 4.2.5 on 2024-02-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_review'),
        ('customer', '0011_remove_userdetails_id_appointmentdetails_user_id_and_more'),
    ]

    operations = [
    ]
