# Generated by Django 4.2.5 on 2024-02-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_merge_20240204_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very Poor')], default=2),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='service_name',
            field=models.CharField(default='Plumbing', max_length=255),
        ),
    ]
